#!/bin/bash
#
# zip-post-commit: have git handle ZIP files by deflating them and storing
#                    the XML in the repository, not the zip file. 
#
#                    companion to zip-pre-commit
#                    must also use this script at post-checkout

# -- config -- #
EXT=$1
ARCHIVE_TYPE=$2
TMP_PREFIX='.~' # prefix XML directory--should NOT conflict with 
                   # anything in your repo

# -- end config -- #

echo
echo "=== Post-commit ZIP processing for .$EXT files ===="

repack_zip () {
    echo "re-zip the directory"
    rm "$1"
    cd "${TMP_PREFIX}$1" && zip "../$1" -r *
    cd ..
}

repack_targzip () {
    echo "re-targzip the directory" 
    rm "$1"
    cd "${TMP_PREFIX}$1" && tar -czf "../$1" *
    cd ..
}

# make it easy to iterate over subdirectories
shopt -s globstar

echo "repack all the zipfiles"
start_dir="$(pwd)"
for i in **/${TMP_PREFIX}*.$EXT; do 
    dir=$(dirname "$i")
    base=$(basename "$i")
    file=${base:${#TMP_PREFIX}}
    cd "$dir"
    
    if [ $ARCHIVE_TYPE == "targzip" ];then
	     repack_targzip "$file"
	   else
						repack_zip "$file"
				fi
				
				
    cd "$start_dir"
done

echo "=== End of post-commit processing ==="
echo
