#!/bin/bash
#
# zip-pre-commit: have git handle ZIP files by deflating them and storing
#                   the XML in the repository, not the zip file. 
#
#                   companion to zip-post-commit
#

# -- config -- #
EXT=$1
ARCHIVE_TYPE=$2
TMP_PREFIX='.~' # prefix XML directory--should NOT conflict with 
                   # anything in your repo

# -- end config -- #

echo
echo "=== Pre-commit ZIP processing for .$EXT $ARCHIVE_TYPE files ===="

unpack_zip () {
    echo "unzip the file: $1 "
    if [ -e "$1" ]; then
        if [ -e "${TMP_PREFIX}$1" ]; then rm -rf "${TMP_PREFIX}$1"; fi
        unzip "$1" -d "${TMP_PREFIX}$1"
    else
        # abort the commit if this isn't an excel file somehow
        echo "$1 is not an ZIP file. this is a bug."
        exit 3
    fi
}

unpack_targzip () {
    echo "untargzip the file: $1 "
    if [ -e "$1" ]; then
        if [ -e "${TMP_PREFIX}$1" ]; then rm -rf "${TMP_PREFIX}$1"; fi
        mkdir "${TMP_PREFIX}$1"
        tar -C "${TMP_PREFIX}$1" -xzvf "$1"
    else
        # abort the commit if this isn't an excel file somehow
        echo "$1 is not an Tar/Gzip file. this is a bug."
        exit 3
    fi
}

replace_with_placeholder () {
	echo "create a placeholder text file for the ZIP file, which uniquely identifies it and prevents losing work on a checkout"
	sha1sum "$1" | tee "$1" > /dev/null # hack for overwriting without temp file
}


reformat_xmls () {
    echo "reformat any xml files to many lines"
    find "$1" -name "*.xml" -type f -exec xmllint --output '{}' --format '{}' \;
}

echo "check that the swap file isn't there (if the ZIP has been staged)"
for i in $(git diff --name-only --cached -- *.$EXT); do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    if [ -e "$dir/~\$$file" ]; then
        echo "$file swap file present: close ZIP file before committing"
        exit 2 # excel file is open
    fi
done


echo "unpack all the zipfiles (if the ZIP has been staged)"
echo $(git diff --name-only --cached -- *.$EXT)
for i in $(git diff --name-only --cached -- *.$EXT); do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    cd "$dir"
    echo -n "Unpack file $dir/$file "
    
    if [ $ARCHIVE_TYPE == "targzip" ];then
	    	unpack_targzip "$file"
	   else
						unpack_zip "$file"
				fi
				
    replace_with_placeholder "$file"
    echo -n "Commit placeholder file: "
    file "$file"
    reformat_xmls "${TMP_PREFIX}$file"
    cd -

    # stage the XML files and the placeholder
    git add "$dir/${TMP_PREFIX}$file"
    git add "$dir/$file"
done

echo "=== End of pre-commit processing ==="
echo

